export type AlfaUniverseAccount = { id: string; name: string; group: string; territory: string; channel: string; subchannel: string };

// Catálogo comercial: 248 cuentas del Universo Canónico Agosto 2026
// (CatHunt/5 Pilares/Universo de clientes/Universo_Clientes_Mexico_Operativo_Agente_9_5.csv,
// UNIVERSO_CANONICO.md). La data transaccional sigue siendo sintética; las cuentas y su
// clasificación de canal ya no se inventan — vienen del mismo universo que usa GO TO MARKET.
export const ALFA_UNIVERSE_ACCOUNTS: readonly AlfaUniverseAccount[] = [
  ["UCM-0001", "Bodega Aurrera", "Walmart de México (Walmex)", "Centro", "Retail Moderno", "Autoservicio popular"],
  ["UCM-0002", "Coppel", "Grupo Coppel", "Noroeste", "Departamental", "Departamental/crédito popular"],
  ["UCM-0003", "Elektra", "Grupo Elektra / Grupo Salinas", "Centro", "Retail Credito", "Electrónica/crédito popular"],
  ["UCM-0004", "Walmart México", "Walmart de México (Walmex)", "Centro", "Retail Moderno", "Autoservicio"],
  ["UCM-0005", "Liverpool", "El Puerto de Liverpool", "Centro", "Departamental", "Departamental nacional"],
  ["UCM-0006", "Super Che", "Grupo Comercial Chedraui", "Golfo/Sureste", "Retail Moderno", "Autoservicio"],
  ["UCM-0007", "Grupo Encanto", "(Individual) Grupo Encanto", "Norte", "Distribuidores", "Distribuidor nacional/regional"],
  ["UCM-0008", "PDH Domésticos", "(Individual) PDH Domésticos", "Centro", "Mayoreo", "Electrodomésticos / cocina"],
  ["UCM-0009", "Casa Ahued", "(Individual) Casa Ahued", "Golfo/Sureste", "Mayoreo", "Hogar / cocina / electrodomésticos"],
  ["UCM-0010", "Amazon México", "", "Nacional", "Ecommerce", "Marketplace"],
  ["UCM-0011", "Chedraui Selecto", "", "Nacional", "Retail Moderno", "Autoservicio"],
  ["UCM-0012", "Hamilton Beach México Comercial", "", "Nacional", "Horeca", "Electrodomésticos cocina; comercial/doméstico"],
  ["UCM-0013", "Mercado Libre México", "", "Nacional", "Ecommerce", "Marketplace"],
  ["UCM-0014", "Oster México", "", "Nacional", "Fabricante", "Marca directa"],
  ["UCM-0015", "Walmart.com.mx", "", "Nacional", "Ecommerce", "Retail e-commerce"],
  ["UCM-0016", "Soriana", "Organización Soriana", "Norte", "Retail Moderno", "Autoservicio"],
  ["UCM-0017", "Chedraui", "Grupo Comercial Chedraui", "Golfo/Sureste", "Retail Moderno", "Autoservicio"],
  ["UCM-0018", "El Bodegón Crédito", "(Individual) El Bodegón Crédito", "Bajío", "Retail Credito", "Crédito regional"],
  ["UCM-0019", "Sears México", "Grupo Sanborns / Grupo Carso", "Centro", "Departamental", "Departamental nacional"],
  ["UCM-0020", "Fresko", "Grupo La Comer", "Centro", "Retail Moderno", "Autoservicio / Premium"],
  ["UCM-0021", "City Market", "Grupo La Comer", "Centro", "Retail Moderno", "Autoservicio / Premium"],
  ["UCM-0022", "Boxito", "(Individual) Boxito", "Sureste", "Distribuidores", "Construcción/hogar"],
  ["UCM-0023", "Central Distribuidora Ojeda", "(Individual) Central Distribuidora Ojeda", "Nacional (sin sede física definida)", "Mayoreo", "Distribuidor / B2B"],
  ["UCM-0024", "Dicom2000", "(Individual) Dicom2000", "Nacional (sin sede física definida)", "Mayoreo", "Mayorista nacional"],
  ["UCM-0025", "Electroking", "(Individual) Electroking", "Centro", "Mayoreo", "Línea blanca / electrodomésticos"],
  ["UCM-0026", "Grupo Ascencio", "(Individual) Grupo Ascencio", "Occidente", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0027", "Inmeza", "(Individual) Inmeza", "Occidente", "Horeca", "Cocinas industriales"],
  ["UCM-0028", "Jugomex", "(Individual) Jugomex", "Centro", "Horeca", "Equipamiento juguerías / foodservice"],
  ["UCM-0029", "Merza", "(Individual) Merza", "Occidente", "Mayoreo", "Autoservicio / mayoreo regional"],
  ["UCM-0030", "Migsa", "(Individual) Migsa", "Centro", "Horeca", "Cocinas industriales"],
  ["UCM-0031", "PiquioMart", "(Individual) PiquioMart", "Centro", "Horeca", "Mayorista / food service"],
  ["UCM-0032", "Torrey Distribución", "(Individual) Torrey Distribución", "Norte", "Horeca", "Equipo comercial/cocina"],
  ["UCM-0033", "Xaze", "(Individual) Xaze", "Centro", "Distribuidores", "Electrónica / hogar"],
  ["UCM-0034", "Zona Chef", "(Individual) Zona Chef", "Nacional (sin sede física definida)", "Horeca", "Equipamiento gastronómico"],
  ["UCM-0035", "Black+Decker México", "", "Nacional", "Fabricante", "Marca directa"],
  ["UCM-0036", "Chedraui.com.mx", "", "Nacional", "Ecommerce", "Retail e-commerce"],
  ["UCM-0037", "Coppel.com", "", "Nacional", "Ecommerce", "Retail e-commerce"],
  ["UCM-0038", "Cyberpuerta", "", "Nacional", "Ecommerce", "Pure player / IT + hogar"],
  ["UCM-0039", "Liverpool.com.mx", "", "Nacional", "Ecommerce", "Retail e-commerce"],
  ["UCM-0040", "PiquioMart Food Service", "", "Nacional", "Horeca", "Equipamiento / foodservice"],
  ["UCM-0041", "Soriana.com", "", "Nacional", "Ecommerce", "Retail e-commerce"],
  ["UCM-0042", "Taurus México", "", "Nacional", "Fabricante", "Marca directa"],
  ["UCM-0043", "Casa Ley", "Casa Ley (familia Ley / Albertsons 49%)", "Noroeste", "Retail Regional", "Autoservicio regional"],
  ["UCM-0044", "HEB México", "H-E-B México", "Norte", "Retail Regional", "Autoservicio regional"],
  ["UCM-0045", "La Comer", "Grupo La Comer", "Centro", "Retail Moderno", "Autoservicio / Premium"],
  ["UCM-0046", "Sodimac México", "Sodimac / Falabella (operado vía Soriana)", "Centro", "Home Improvement", "Mejoras para el hogar"],
  ["UCM-0047", "Veana", "(Individual) Veana", "Nacional (sin sede física definida)", "Distribuidores", "Retail regional"],
  ["UCM-0048", "Koblenz México", "", "Nacional", "Fabricante", "Marca directa"],
  ["UCM-0049", "Ninja Kitchen México", "", "Nacional", "Fabricante", "Marca directa"],
  ["UCM-0050", "The Home Depot México", "", "Nacional", "Home Improvement", "Mejoras para el hogar"],
  ["UCM-0051", "Neto", "Tiendas Neto (Grupo Salinas via Banco Azteca? validar)", "Centro", "Retail Nacional", "Autoservicio popular"],
  ["UCM-0052", "Dunosusa", "Dunosusa (Proveedora del Panadero)", "Sureste", "Retail Regional", "Autoservicio regional"],
  ["UCM-0053", "Suburbia", "El Puerto de Liverpool", "Centro", "Departamental", "Departamental popular"],
  ["UCM-0054", "Sanborns", "Grupo Sanborns / Grupo Carso", "Centro", "Departamental", "Tienda departamental/restaurante"],
  ["UCM-0055", "Grupo Roga", "Grupo Roga (Villarreal Muebles / El Pasito)", "Norte", "Mueblerias", "Muebles/electrodomésticos"],
  ["UCM-0056", "Home Depot", "The Home Depot México", "Norte", "Home Improvement", "Home improvement"],
  ["UCM-0057", "Del Sol", "Grupo Comercial Control (Del Sol / Woolworth)", "Norte", "Departamental", "Departamental popular"],
  ["UCM-0058", "Calimax", "Calimax (Grupo Calimax)", "Noroeste", "Retail Regional", "Autoservicio regional"],
  ["UCM-0059", "Alsuper", "Grupo Futurama (Alsuper / S-Mart / Fresh Market)", "Norte", "Retail Regional", "Autoservicio regional"],
  ["UCM-0060", "CT Internacional", "(Individual) CT Internacional", "Noroeste", "Mayoreo", "Tecnología / electrónica"],
  ["UCM-0061", "Costco México", "Costco Wholesale México", "Centro", "Clubes de Precio", "Club mayorista"],
  ["UCM-0062", "Cristalería La Única", "", "Nacional", "Distribuidor regional", "Cristalería / institucional"],
  ["UCM-0063", "El Palacio de Hierro", "Grupo Palacio de Hierro", "Centro", "Departamental", "Departamental premium"],
  ["UCM-0064", "Global Office", "", "Nacional", "Ecommerce", "Oficina / B2B"],
  ["UCM-0065", "Mega Outlet Fernández", "(Individual) Mega Outlet Fernández", "Centro", "Retail Regional", "Outlet / línea blanca"],
  ["UCM-0066", "Aguilar Refacciones", "(Individual) Aguilar Refacciones", "Nacional (sin sede física definida)", "Especialistas", "Refacciones electrodomésticos"],
  ["UCM-0067", "Alkia", "(Individual) Alkia", "Bajío", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0068", "Arteli", "(Individual) Arteli", "Norte", "Retail Regional", "Autoservicio regional"],
  ["UCM-0069", "Berista", "(Individual) Berista", "Centro", "Horeca", "Café / foodservice"],
  ["UCM-0070", "CVA Mayoreo", "(Individual) CVA Mayoreo", "Occidente", "Mayoreo", "Tecnología / electrónica"],
  ["UCM-0071", "Casa Cravioto", "(Individual) Casa Cravioto", "Centro", "Especialistas", "Ferretería / hogar"],
  ["UCM-0072", "Casa Marcus", "(Individual) Casa Marcus", "Centro", "Mayoreo", "Mayorista / tienda centro"],
  ["UCM-0073", "Central de Cocinas Industriales", "(Individual) Central de Cocinas Industriales", "Nacional (sin sede física definida)", "Horeca", "Cocinas industriales"],
  ["UCM-0074", "Cocinas Institucionales", "(Individual) Cocinas Institucionales", "Nacional (sin sede física definida)", "Horeca", "Cocinas industriales"],
  ["UCM-0075", "Electros para Casa", "(Individual) Electros para Casa", "Nacional (sin sede física definida)", "Especialistas", "Cocinas/equipos"],
  ["UCM-0076", "Equipos Monterrey", "(Individual) Equipos Monterrey", "Norte", "Horeca", "Equipo cocina/foodservice"],
  ["UCM-0077", "Equipos de Cocina México", "(Individual) Equipos de Cocina México", "Nacional (sin sede física definida)", "Horeca", "Cocinas industriales"],
  ["UCM-0078", "Ferrihogar", "(Individual) Ferrihogar", "Nacional (sin sede física definida)", "Mayoreo", "Refacciones / mayoreo"],
  ["UCM-0079", "Grupo Alpha Food Service", "(Individual) Grupo Alpha Food Service", "Nacional (sin sede física definida)", "Horeca", "Foodservice"],
  ["UCM-0080", "Hogar y Equipos del Norte", "(Individual) Hogar y Equipos del Norte", "Norte", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0081", "Integra Hogar", "(Individual) Integra Hogar", "Norte", "Distribuidores", "Distribuidor / showroom"],
  ["UCM-0082", "Mayoreo Electromecánico", "(Individual) Mayoreo Electromecánico", "Occidente", "Distribuidores", "Refacciones / servicio"],
  ["UCM-0083", "Merco", "(Individual) Merco", "Norte", "Retail Regional", "Autoservicio regional"],
  ["UCM-0084", "Mueblería Elizondo", "(Individual) Mueblería Elizondo", "Norte", "Mueblerias", "Muebles/electrodomésticos"],
  ["UCM-0085", "Mueblerías Valdez Baluarte", "(Individual) Mueblerías Valdez Baluarte", "Noroeste", "Mueblerias", "Muebles/electrodomésticos"],
  ["UCM-0086", "Muebles América", "(Individual) Muebles América", "Occidente", "Mueblerias", "Muebles/electrodomésticos"],
  ["UCM-0087", "PCH Mayoreo", "(Individual) PCH Mayoreo", "Occidente", "Mayoreo", "Tecnología / electrónica"],
  ["UCM-0088", "Patlán", "(Individual) Patlán", "Norte", "Distribuidores", "Tienda / distribución"],
  ["UCM-0089", "S-Mart", "(Individual) S-Mart", "Norte", "Retail Regional", "Autoservicio regional"],
  ["UCM-0090", "Smart", "(Individual) Smart", "Norte", "Retail Regional", "Autoservicio regional"],
  ["UCM-0091", "Super Willys", "(Individual) Super Willys", "Sureste", "Retail Regional", "Autoservicio regional"],
  ["UCM-0092", "SuperMayorista", "(Individual) SuperMayorista", "Centro", "Mayoreo", "Mayoreo digital"],
  ["UCM-0093", "Zorro Abarrotero", "(Individual) Zorro Abarrotero", "Centro", "Mayoreo", "Abarrotero mayorista"],
  ["UCM-0094", "Barper Cocina", "", "Nacional", "Distribuidor regional", "Tienda / cocina"],
  ["UCM-0095", "Claro Shop", "", "Nacional", "Ecommerce", "Marketplace"],
  ["UCM-0096", "Electrodomésticos Baratos CDMX", "", "Nacional", "Distribuidor regional", "Medio mayoreo"],
  ["UCM-0097", "Ferrepat", "", "Nacional", "Ecommerce", "Ferretería online"],
  ["UCM-0098", "Linio", "", "Nacional", "Ecommerce", "Marketplace"],
  ["UCM-0099", "Sears.com.mx", "", "Nacional", "Ecommerce", "Retail e-commerce"],
  ["UCM-0100", "Superflama", "", "Nacional", "Especializado", "Hogar / gas / electrodomésticos"],
  ["UCM-0101", "Marchand", "(Individual) Marchand", "Centro", "Especialistas", "Papelería/hogar"],
  ["UCM-0102", "BM Santa Catarina", "(Individual) BM Santa Catarina", "Centro", "Mueblerias", "Línea blanca, muebles"],
  ["UCM-0103", "Aká Superbodega", "(Individual) Aká Superbodega", "Sureste", "Retail Regional", "Autoservicio regional"],
  ["UCM-0104", "Bodega del Hogar", "(Individual) Bodega del Hogar", "Nacional (sin sede física definida)", "Especialistas", "Hogar/electrodomésticos"],
  ["UCM-0105", "Casa Díaz Occidente", "(Individual) Casa Díaz Occidente", "Occidente", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0106", "Casa Hernández", "(Individual) Casa Hernández", "Norte", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0107", "Casa Montes", "(Individual) Casa Montes", "Centro", "Mayoreo", "Artículos de cocina; posible complemento electrodoméstico"],
  ["UCM-0108", "Comercial Campeche", "(Individual) Comercial Campeche", "Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0109", "Comercial Celaya", "(Individual) Comercial Celaya", "Bajío", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0110", "Comercial Irapuato", "(Individual) Comercial Irapuato", "Bajío", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0111", "Comercial León", "(Individual) Comercial León", "Bajío", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0112", "Comercial Queretana", "(Individual) Comercial Queretana", "Bajío", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0113", "Comercial Villahermosa", "(Individual) Comercial Villahermosa", "Golfo/Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0114", "Comercial Zamora", "(Individual) Comercial Zamora", "Occidente", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0115", "Comercial de Occidente", "(Individual) Comercial de Occidente", "Occidente", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0116", "Comercial del Norte", "(Individual) Comercial del Norte", "Norte", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0117", "Cosmos Línea Blanca", "(Individual) Cosmos Línea Blanca", "Nacional", "B2B", "Línea blanca; cotizaciones"],
  ["UCM-0118", "Dcocina", "(Individual) Dcocina", "Centro", "Distribuidores", "Utensilios, cocina hogar"],
  ["UCM-0119", "Distribuidora Bajío", "(Individual) Distribuidora Bajío", "Bajío", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0120", "Distribuidora Colima", "(Individual) Distribuidora Colima", "Occidente", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0121", "Distribuidora Peninsular", "(Individual) Distribuidora Peninsular", "Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0122", "Distribuidora Regia", "(Individual) Distribuidora Regia", "Norte", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0123", "Distribuidora Salamanca", "(Individual) Distribuidora Salamanca", "Bajío", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0124", "Distribuidora Tabasco", "(Individual) Distribuidora Tabasco", "Golfo/Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0125", "Distribuidora Tuxtla", "(Individual) Distribuidora Tuxtla", "Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0126", "EPS Electro-Partes", "(Individual) EPS Electro-Partes", "Noroeste", "Especialistas", "Refacciones línea blanca/electrodomésticos"],
  ["UCM-0127", "El Florido", "(Individual) El Florido", "Noroeste", "Retail Regional", "Autoservicio regional"],
  ["UCM-0128", "Euroelectrica", "(Individual) Euroelectrica", "Nacional (sin sede física definida)", "Especialistas", "Electrodomésticos/línea blanca"],
  ["UCM-0129", "Exel del Norte", "(Individual) Exel del Norte", "Norte", "Mayoreo", "Tecnología/electrónica"],
  ["UCM-0130", "Famsa", "(Individual) Famsa", "Norte", "Departamental", "Muebles/electrodomésticos"],
  ["UCM-0131", "Fantasías Miguel", "(Individual) Fantasías Miguel", "Centro", "Especialistas", "Manualidades/hogar"],
  ["UCM-0132", "Foly Muebles", "(Individual) Foly Muebles", "Norte", "Mueblerias", "Línea blanca; electrodomésticos menor no confirmado"],
  ["UCM-0133", "Garcés", "(Individual) Garcés", "Sur", "Retail Regional", "Autoservicio regional"],
  ["UCM-0134", "Grupo Cancún Comercial", "(Individual) Grupo Cancún Comercial", "Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0135", "Grupo Chiapas Comercial", "(Individual) Grupo Chiapas Comercial", "Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0136", "Grupo Cozumel", "(Individual) Grupo Cozumel", "Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0137", "Grupo Gonher", "(Individual) Grupo Gonher", "Norte", "Distribuidores", "Autopartes/retail regional"],
  ["UCM-0138", "Grupo Logístico Potosino", "(Individual) Grupo Logístico Potosino", "Bajío", "Distribuidores", "Logística/comercial"],
  ["UCM-0139", "Grupo Mérida Hogar", "(Individual) Grupo Mérida Hogar", "Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0140", "Grupo QP", "(Individual) Grupo QP", "Occidente", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0141", "Grupo Vallarta", "(Individual) Grupo Vallarta", "Occidente", "Distribuidores", "Retail/regional"],
  ["UCM-0142", "Grupo Vega", "(Individual) Grupo Vega", "Bajío", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0143", "Kitchen Market", "(Individual) Kitchen Market", "Centro", "Especialistas", "Cocina"],
  ["UCM-0144", "La Marina", "(Individual) La Marina", "Golfo/Sureste", "Retail Regional", "Línea blanca, electrodomésticos, hogar"],
  ["UCM-0145", "MAHA", "(Individual) MAHA", "Norte", "Mayoreo", "Artículos de cocina precio mayoreo"],
  ["UCM-0146", "Mayoreo Cárdenas", "(Individual) Mayoreo Cárdenas", "Occidente", "Distribuidores", "Canal ferretero/hogar"],
  ["UCM-0147", "Mueblería Standard", "(Individual) Mueblería Standard", "Nacional (sin sede física definida)", "Distribuidores", "Hogar / muebles / línea blanca"],
  ["UCM-0148", "Muebles Dico Occidente", "(Individual) Muebles Dico Occidente", "Occidente", "Mueblerias", "Muebles/hogar"],
  ["UCM-0149", "Nalúa Outlet", "(Individual) Nalúa Outlet", "Bajío", "Otros", "Outlet línea blanca/electrodomésticos"],
  ["UCM-0150", "Rational México", "(Individual) Rational México", "Centro", "Horeca", "Equipo profesional"],
  ["UCM-0151", "Riviera Distribución", "(Individual) Riviera Distribución", "Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UCM-0152", "Rosan Internacional", "(Individual) Rosan Internacional", "Centro", "Especialistas", "Refacciones licuadora/electrodomésticos"],
  ["UCM-0153", "Tiendas Garcés", "(Individual) Tiendas Garcés", "Sur", "Retail Regional", "Autoservicio regional"],
  ["UCM-0154", "Truper Expert", "(Individual) Truper Expert", "Centro", "Especialistas", "Ferretería"],
  ["UCM-0155", "Vianney Hogar", "(Individual) Vianney Hogar", "Bajío", "Especialistas", "Hogar/textil"],
  ["UCM-0156", "Alsuper Store", "", "Nacional", "Retail", "Autoservicio regional"],
  ["UCM-0157", "Casa Marchand", "", "Nacional", "Retail Regional", "Autoservicio regional"],
  ["UCM-0158", "Hamilton Beach México", "", "Nacional", "Marca benchmark / canal directo", "Electrodomésticos cocina; comercial/doméstico"],
  ["UCM-0159", "Oster México / Newell", "", "Nacional", "Marca benchmark / canal directo", "Licuadoras, cafeteras, hornos, cocina/hogar"],
  ["UCM-0160", "Tiendas Neto", "", "Nacional", "Retail Regional", "Autoservicio regional"],
  ["UCM-0161", "Turmix de México", "", "Nacional", "Marca objetivo", "Extractores, licuadoras, purificadores"],
  ["UCM-0162", "Grupo Ascencio / DEASA", "", "Occidente", "Distribuidor regional", "Canal ferretero/electrodoméstico complementario"],
  ["UCM-0163", "Electrodomésticos Olvera Madero Pte", "", "Norte", "Sucursal regional", "Refacciones/electrodomésticos"],
  ["UCM-0164", "Waldos Dollar Mart", "Waldos Dollar Mart de México", "Nacional", "Especialistas", "Variedades / precio bajo"],
  ["UCM-0165", "Ryse Delta", "", "Bajío", "Sucursal regional", "Enseres menores, línea blanca, negocio"],
  ["UCM-0166", "Office Depot México", "Office Depot de México", "Nacional", "Especialistas", "Oficina / ecommerce"],
  ["UCM-0167", "Sam's Club México", "Walmart de México (Walmex)", "Nacional", "Clubes de Precio", "Electrodomésticos de cocina, línea blanca"],
  ["UCM-0168", "Tiendas Atlas", "(Individual) Tiendas Atlas", "Nacional", "Mueblerias", "Hogar / muebles"],
  ["UCM-0169", "El Bodegón", "", "Occidente", "Retail regional con venta en línea", "Línea blanca y electrodomésticos"],
  ["UCM-0170", "OfficeMax México", "Operadora OMX (OfficeMax México)", "Nacional", "Especialistas", "Oficina / ecommerce"],
  ["UCM-0171", "Mayoreo Libre", "", "Centro", "Mayorista ecommerce/bodega", "Electrodomésticos, línea blanca, hogar"],
  ["UCM-0172", "City Club", "Organización Soriana (City Club)", "Nacional", "Clubes de Precio", "Electrodomésticos al mayoreo"],
  ["UCM-0173", "Anforama", "Comercial Anforama", "Nacional", "Especialistas", "Hogar / cocina"],
  ["UCM-0174", "Radio Shack México", "Grupo Gigante (RadioShack)", "Nacional", "Especialistas", "Electrónica"],
  ["UCM-0175", "Smart & Final del Noroeste", "Smart & Final del Noroeste (JV Chedraui/Calimax)", "Noroeste", "Mayoreo", "Mayoreo autoservicio"],
  ["UCM-0176", "Cimaco", "Cía. Comercial Cimaco", "Norte", "Departamental", "Departamental"],
  ["UCM-0177", "Electrodomésticos Olvera", "(Individual) Electrodomésticos Olvera Matriz", "Norte", "Especialistas", "Refacciones licuadora, electrodomésticos, equipo industrial"],
  ["UCM-0178", "Tiendas Chapur", "(Individual) Tiendas Chapur", "Sureste", "Departamental", "Departamental"],
  ["UCM-0179", "La Proveedora del Hogar / PDH", "(Individual) La Proveedora del Hogar / PDH", "Centro", "Horeca", "Licuadoras, extractores, cafeteras, negocio/restaurante"],
  ["UCM-0180", "CDO", "", "Centro", "Distribuidor / ecommerce B2B", "Licuadoras, fuentes de soda, cafeteras, hornos, línea blanca"],
  ["UCM-0181", "Todo por Mayoreo", "", "Nacional", "Mayorista nacional B2B ecommerce", "Línea blanca, licuadoras, hornos, aspiradoras, cafeteras"],
  ["UCM-0182", "19 Hermanos", "(Individual) 19 Hermanos", "Occidente", "Mayoreo", "Mayorista abarrotero"],
  ["UCM-0183", "Abarrotera Fuentes", "(Individual) Abarrotera Fuentes", "Centro", "Mayoreo", "Mayorista abarrotero"],
  ["UCM-0184", "Abarrotes La Violeta", "(Individual) Abarrotes La Violeta", "Occidente", "Mayoreo", "Mayorista abarrotero"],
  ["UCM-0185", "Abastecedora Comercial de Parral", "(Individual) Abastecedora Comercial de Parral", "Norte", "Mayoreo", "Mayorista abarrotero"],
  ["UCM-0186", "Abasteo", "(Individual) Abasteo", "Nacional", "B2B", "Batidoras, cafeteras, electrodomésticos para empresa"],
  ["UCM-0187", "Almacenes Anfora", "(Individual) Almacenes Anfora", "Nacional", "Especialistas", "Hogar / cocina"],
  ["UCM-0188", "Almacenes García", "(Individual) Almacenes García", "Nacional", "Departamental", "Departamental"],
  ["UCM-0189", "Aluz", "(Individual) Aluz", "Norte", "B2B", "Línea blanca"],
  ["UCM-0190", "Casa Lupita", "(Individual) Casa Lupita", "Occidente", "Mayoreo", "Mayorista abarrotero"],
  ["UCM-0191", "Centro Comercial Cruz Azul", "(Individual) Centro Comercial Cruz Azul", "Centro", "Retail Regional", "Autoservicio"],
  ["UCM-0192", "Chef Market", "(Individual) Chef Market", "Centro", "Mayoreo", "Cocina, hogar, electrodomésticos"],
  ["UCM-0193", "Cocinas y Equipamientos B&P", "(Individual) Cocinas y Equipamientos B&P", "Occidente", "B2B", "Línea blanca / equipamiento"],
  ["UCM-0194", "Comercial Balandra", "(Individual) Comercial Balandra", "Noroeste", "Retail Regional", "Línea blanca, electrodomésticos, electrónica"],
  ["UCM-0195", "Comercial San Luis", "(Individual) Comercial San Luis", "Bajío", "Retail Regional", "Línea blanca, electrodomésticos"],
  ["UCM-0196", "Comercial Treviño", "(Individual) Comercial Treviño", "Norte", "Mayoreo", "Mayorista abarrotero"],
  ["UCM-0197", "Comercializadora JM", "(Individual) Comercializadora JM", "Norte", "Mayoreo", "Mayorista abarrotero"],
  ["UCM-0198", "Cosaltor", "(Individual) Cosaltor", "Centro", "B2B", "Línea blanca"],
  ["UCM-0199", "Damsa / La Mixteca", "(Individual) Damsa / La Mixteca", "Centro", "Mayoreo", "Mayorista abarrotero"],
  ["UCM-0200", "Decasa", "(Individual) Decasa", "Bajío", "Mayoreo", "Mayorista abarrotero"],
  ["UCM-0201", "Disroga", "(Individual) Disroga", "Centro", "Mayoreo", "Mayorista abarrotero"],
  ["UCM-0202", "Distribuidora Hugos", "(Individual) Distribuidora Hugos", "Occidente", "Mayoreo", "Mayorista abarrotero"],
  ["UCM-0203", "El Nuevo Mundo", "(Individual) El Nuevo Mundo", "Centro", "Departamental", "Departamental"],
  ["UCM-0204", "El Rey de Corregidora", "(Individual) El Rey de Corregidora", "Centro", "Mayoreo", "Enseres menores, licuadoras, cafeteras, hornos, electrónica"],
  ["UCM-0205", "Expansión DI", "(Individual) Expansión DI", "Centro", "B2B", "Línea blanca"],
  ["UCM-0206", "Fénix El Super de Casa", "(Individual) Fénix El Super de Casa", "Golfo/Sureste", "Retail Regional", "Autoservicio"],
  ["UCM-0207", "Grupo Casa Rodríguez", "(Individual) Grupo Casa Rodríguez", "Centro", "Horeca", "Equipamiento cocina, utensilios, horeca"],
  ["UCM-0208", "Grupo Cevisa", "(Individual) Grupo Cevisa", "Centro", "Mayoreo", "Línea blanca, muebles, electrónica, electrodomésticos"],
  ["UCM-0209", "Grupo Venegas", "(Individual) Grupo Venegas", "Norte", "Mayoreo", "Mayorista abarrotero"],
  ["UCM-0210", "HG Avante", "(Individual) HG Avante", "Golfo/Sureste", "B2B", "Línea blanca"],
  ["UCM-0211", "Hemsa", "(Individual) Hemsa", "Norte", "Departamental", "Departamental"],
  ["UCM-0212", "La Misión Supermercados", "(Individual) La Misión Supermercados", "Noroeste", "Retail Regional", "Autoservicio"],
  ["UCM-0213", "Línea Blanca Giil", "(Individual) Línea Blanca Giil", "Centro", "B2B", "Línea blanca"],
  ["UCM-0214", "Maz Zumpango", "(Individual) Maz Zumpango", "Centro", "Mayoreo", "Mayorista abarrotero"],
  ["UCM-0215", "Mercado Mayco", "(Individual) Mercado Mayco", "Norte", "Mayoreo", "Mayorista abarrotero"],
  ["UCM-0216", "Mercantil del Hogar", "(Individual) Mercantil del Hogar", "Centro", "Mayoreo", "Licuadoras, refacciones, cafeteras, ollas, estufas"],
  ["UCM-0217", "Multimarcas del Bajío", "(Individual) Multimarcas del Bajío", "Bajío", "Mayoreo", "Enseres menores y línea blanca"],
  ["UCM-0218", "Más Bodega y Logística", "(Individual) Más Bodega y Logística", "Noroeste", "Retail Regional", "Autoservicio"],
  ["UCM-0219", "Nieto Comercial", "(Individual) Nieto Comercial", "Centro", "Mayoreo", "Mayorista abarrotero"],
  ["UCM-0220", "Ofix", "(Individual) Ofix", "Nacional", "Especialistas", "Oficina / ecommerce"],
  ["UCM-0221", "Organización CIR", "(Individual) Organización CIR", "Occidente", "Mayoreo", "Mayorista abarrotero"],
  ["UCM-0222", "PDH Puebla", "(Individual) PDH Puebla", "Centro", "Retail Regional", "Enseres menores/electrodomésticos"],
  ["UCM-0223", "PDH Veracruz", "(Individual) PDH Veracruz", "Golfo/Sureste", "Retail Regional", "Enseres menores/electrodomésticos"],
  ["UCM-0224", "Piticó", "(Individual) Piticó", "Sureste", "Retail Regional", "Autoservicio"],
  ["UCM-0225", "Productos Básicos de Córdoba", "(Individual) Productos Básicos de Córdoba", "Golfo/Sureste", "B2B", "Línea blanca"],
  ["UCM-0226", "Proper Services", "(Individual) Proper Services", "Centro", "Mayoreo", "Licuadoras, extractores, cafeteras, línea blanca, incentivos"],
  ["UCM-0227", "Proveedora Diez", "(Individual) Proveedora Diez", "Centro", "Horeca", "Cocina profesional, cafeterías, restaurantes"],
  ["UCM-0228", "RG Audio y Video", "(Individual) RG Audio y Video", "Centro", "B2B", "Línea blanca / electrónica"],
  ["UCM-0229", "Ryse", "(Individual) Ryse", "Bajío", "Mayoreo", "Enseres menores, línea blanca, refacciones, comercial"],
  ["UCM-0230", "Satus Inteligencia Comercial", "(Individual) Satus Inteligencia Comercial", "Centro", "B2B", "Línea blanca"],
  ["UCM-0231", "Steren", "(Individual) Steren", "Nacional", "Especialistas", "Electrónica"],
  ["UCM-0232", "Su Bodega", "(Individual) Su Bodega", "Golfo/Sureste", "Retail Regional", "Autoservicio"],
  ["UCM-0233", "Su Plaza", "(Individual) Su Plaza", "Centro", "Retail Regional", "Autoservicio"],
  ["UCM-0234", "Supermercados Aramburo", "(Individual) Supermercados Aramburo", "Noroeste", "Retail Regional", "Autoservicio"],
  ["UCM-0235", "Surtiloza", "(Individual) Surtiloza", "Occidente", "B2B", "Cocina profesional y hogar"],
  ["UCM-0236", "Súper Gutiérrez", "(Individual) Súper Gutiérrez", "Norte", "Retail Regional", "Autoservicio"],
  ["UCM-0237", "Súper San Francisco de Asís", "(Individual) Súper San Francisco de Asís", "Sureste", "Retail Regional", "Autoservicio"],
  ["UCM-0238", "The Home Store", "(Individual) The Home Store", "Nacional", "Especialistas", "Hogar"],
  ["UCM-0239", "El Bodegón Colima Centro", "", "Occidente", "Sucursal regional", "Línea blanca y electrodomésticos"],
  ["UCM-0240", "Electrodomésticos Olvera Chihuahua", "", "Norte", "Sucursal regional", "Refacciones/electrodomésticos"],
  ["UCM-0241", "Electrodomésticos Olvera Matriz", "", "Norte", "Regional refacciones/equipo industrial/electrodomésticos", "Refacciones licuadora, electrodomésticos, equipo industrial"],
  ["UCM-0242", "Electrodomésticos Olvera Reynosa", "", "Norte", "Sucursal regional", "Refacciones/electrodomésticos"],
  ["UCM-0243", "Electrodomésticos Olvera Saltillo", "", "Norte", "Sucursal regional", "Refacciones/electrodomésticos/equipo industrial"],
  ["UCM-0244", "Global Office / Distribuidor Oster Guadalajara", "", "Occidente", "Distribuidor ecommerce regional", "Electrodomésticos, licuadoras, purificadores Turmix"],
  ["UCM-0245", "Grupo Ascencio / AIESA", "", "Occidente", "Distribuidor regional multi-sucursal", "Más eléctrico que electrodoméstico; posible canal ferretero"],
  ["UCM-0246", "Jugomex / Comercializadora Berista", "", "Centro", "Distribuidor autorizado Hamilton Beach Comercial", "Fuentes de soda, cafeteras, equipo comercial"],
  ["UCM-0247", "Proveedora del Hogar / proveedoradelhogar.com.mx", "", "Centro", "Mayorista / institucional horeca", "Licuadoras, extractores, cafeteras, negocio/restaurante"],
  ["UCM-0248", "Saesa Trading", "", "Centro", "Distribuidor/mayoreo ecommerce", "Electrodomésticos en paquetes/cajas"],

].map(([id, name, group, territory, channel, subchannel]) => ({ id, name, group, territory, channel, subchannel })) as readonly AlfaUniverseAccount[];
