export type AlfaUniverseAccount = { id: string; name: string; group: string; territory: string; channel: string; subchannel: string };

// Catálogo comercial: 248 cuentas del Universo Canónico Agosto 2026
// Jerarquía de 8 canales oficiales de CatHunt (CANONICOS/data/universo_canonico.json).
// La data transaccional sigue siendo sintética; las cuentas y su clasificación de canal
// vienen del dataset canónico centralizado.
export const ALFA_UNIVERSE_ACCOUNTS: readonly AlfaUniverseAccount[] = [
  ["UCM-0001","Bodega Aurrera","Walmart de México (Walmex)","Centro","Retail / autoservicio","General"],
  ["UCM-0002","Coppel","Grupo Coppel","Noroeste","Retail / autoservicio","Departamental"],
  ["UCM-0003","Elektra","Grupo Elektra / Grupo Salinas","Centro","Retail / autoservicio","General"],
  ["UCM-0004","Walmart México","Walmart de México (Walmex)","Centro","Retail / autoservicio","General"],
  ["UCM-0005","Liverpool","El Puerto de Liverpool","Centro","Retail / autoservicio","Departamental"],
  ["UCM-0006","Super Che","Grupo Comercial Chedraui","Golfo/Sureste","Retail / autoservicio","General"],
  ["UCM-0007","Grupo Encanto","(Individual) Grupo Encanto","Norte","Distribuidor","Regional"],
  ["UCM-0008","PDH Domésticos","(Individual) PDH Domésticos","Centro","Mayorista","General"],
  ["UCM-0009","Casa Ahued","(Individual) Casa Ahued","Golfo/Sureste","Mayorista","General"],
  ["UCM-0010","Amazon México","","Nacional","Marketplace / e-commerce","Pure player"],
  ["UCM-0011","Chedraui Selecto","","Nacional","Retail / autoservicio","Premium"],
  ["UCM-0012","Hamilton Beach México Comercial","","Nacional","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0013","Mercado Libre México","","Nacional","Marketplace / e-commerce","Pure player"],
  ["UCM-0014","Oster México","","Nacional","Marca / fabricante","General"],
  ["UCM-0015","Walmart.com.mx","","Nacional","Marketplace / e-commerce","Híbrido"],
  ["UCM-0016","Soriana","Organización Soriana","Norte","Retail / autoservicio","General"],
  ["UCM-0017","Chedraui","Grupo Comercial Chedraui","Golfo/Sureste","Retail / autoservicio","General"],
  ["UCM-0018","El Bodegón Crédito","(Individual) El Bodegón Crédito","Bajío","Retail / autoservicio","Cadena regional"],
  ["UCM-0019","Sears México","Grupo Sanborns / Grupo Carso","Centro","Retail / autoservicio","Departamental"],
  ["UCM-0020","Fresko","Grupo La Comer","Centro","Retail / autoservicio","Premium"],
  ["UCM-0021","City Market","Grupo La Comer","Centro","Retail / autoservicio","Premium"],
  ["UCM-0022","Boxito","(Individual) Boxito","Sureste","Distribuidor","General"],
  ["UCM-0023","Central Distribuidora Ojeda","(Individual) Central Distribuidora Ojeda","Nacional (sin sede física definida)","Mayorista","General"],
  ["UCM-0024","Dicom2000","(Individual) Dicom2000","Nacional (sin sede física definida)","Mayorista","General"],
  ["UCM-0025","Electroking","(Individual) Electroking","Centro","Mayorista","General"],
  ["UCM-0026","Grupo Ascencio","(Individual) Grupo Ascencio","Occidente","Distribuidor","General"],
  ["UCM-0027","Inmeza","(Individual) Inmeza","Occidente","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0028","Jugomex","(Individual) Jugomex","Centro","Línea blanca / especialista","General"],
  ["UCM-0029","Merza","(Individual) Merza","Occidente","Mayorista","General"],
  ["UCM-0030","Migsa","(Individual) Migsa","Centro","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0031","PiquioMart","(Individual) PiquioMart","Centro","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0032","Torrey Distribución","(Individual) Torrey Distribución","Norte","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0033","Xaze","(Individual) Xaze","Centro","Distribuidor","General"],
  ["UCM-0034","Zona Chef","(Individual) Zona Chef","Nacional (sin sede física definida)","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0035","Black+Decker México","","Nacional","Marca / fabricante","General"],
  ["UCM-0036","Chedraui.com.mx","","Nacional","Marketplace / e-commerce","Híbrido"],
  ["UCM-0037","Coppel.com","","Nacional","Marketplace / e-commerce","Híbrido"],
  ["UCM-0038","Cyberpuerta","","Nacional","Marketplace / e-commerce","Pure player"],
  ["UCM-0039","Liverpool.com.mx","","Nacional","Marketplace / e-commerce","Híbrido"],
  ["UCM-0040","PiquioMart Food Service","","Nacional","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0041","Soriana.com","","Nacional","Marketplace / e-commerce","Híbrido"],
  ["UCM-0042","Taurus México","","Nacional","Marca / fabricante","General"],
  ["UCM-0043","Casa Ley","Casa Ley (familia Ley / Albertsons 49%)","Noroeste","Retail / autoservicio","Cadena regional"],
  ["UCM-0044","HEB México","H-E-B México","Norte","Retail / autoservicio","Cadena regional"],
  ["UCM-0045","La Comer","Grupo La Comer","Centro","Retail / autoservicio","Premium"],
  ["UCM-0046","Sodimac México","Sodimac / Falabella (operado vía Soriana)","Centro","Home improvement","General"],
  ["UCM-0047","Veana","(Individual) Veana","Nacional (sin sede física definida)","Distribuidor","Regional"],
  ["UCM-0048","Koblenz México","","Nacional","Marca / fabricante","General"],
  ["UCM-0049","Ninja Kitchen México","","Nacional","Marca / fabricante","General"],
  ["UCM-0050","The Home Depot México","","Nacional","Home improvement","General"],
  ["UCM-0051","Neto","Tiendas Neto (Grupo Salinas via Banco Azteca? validar)","Centro","Retail / autoservicio","General"],
  ["UCM-0052","Dunosusa","Dunosusa (Proveedora del Panadero)","Sureste","Retail / autoservicio","Cadena regional"],
  ["UCM-0053","Suburbia","El Puerto de Liverpool","Centro","Retail / autoservicio","Departamental"],
  ["UCM-0054","Sanborns","Grupo Sanborns / Grupo Carso","Centro","Retail / autoservicio","Departamental"],
  ["UCM-0055","Grupo Roga","Grupo Roga (Villarreal Muebles / El Pasito)","Norte","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0056","Home Depot","The Home Depot México","Norte","Home improvement","General"],
  ["UCM-0057","Del Sol","Grupo Comercial Control (Del Sol / Woolworth)","Norte","Retail / autoservicio","Departamental"],
  ["UCM-0058","Calimax","Calimax (Grupo Calimax)","Noroeste","Retail / autoservicio","Cadena regional"],
  ["UCM-0059","Alsuper","Grupo Futurama (Alsuper / S-Mart / Fresh Market)","Norte","Retail / autoservicio","Cadena regional"],
  ["UCM-0060","CT Internacional","(Individual) CT Internacional","Noroeste","Mayorista","General"],
  ["UCM-0061","Costco México","Costco Wholesale México","Centro","Retail / autoservicio","Club de precios"],
  ["UCM-0062","Cristalería La Única","","Nacional","Distribuidor","General"],
  ["UCM-0063","El Palacio de Hierro","Grupo Palacio de Hierro","Centro","Retail / autoservicio","Premium"],
  ["UCM-0064","Global Office","","Nacional","Marketplace / e-commerce","General"],
  ["UCM-0065","Mega Outlet Fernández","(Individual) Mega Outlet Fernández","Centro","Retail / autoservicio","General"],
  ["UCM-0066","Aguilar Refacciones","(Individual) Aguilar Refacciones","Nacional (sin sede física definida)","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0067","Alkia","(Individual) Alkia","Bajío","Distribuidor","General"],
  ["UCM-0068","Arteli","(Individual) Arteli","Norte","Retail / autoservicio","Cadena regional"],
  ["UCM-0069","Berista","(Individual) Berista","Centro","Línea blanca / especialista","General"],
  ["UCM-0070","CVA Mayoreo","(Individual) CVA Mayoreo","Occidente","Mayorista","General"],
  ["UCM-0071","Casa Cravioto","(Individual) Casa Cravioto","Centro","Línea blanca / especialista","General"],
  ["UCM-0072","Casa Marcus","(Individual) Casa Marcus","Centro","Mayorista","General"],
  ["UCM-0073","Central de Cocinas Industriales","(Individual) Central de Cocinas Industriales","Nacional (sin sede física definida)","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0074","Cocinas Institucionales","(Individual) Cocinas Institucionales","Nacional (sin sede física definida)","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0075","Electros para Casa","(Individual) Electros para Casa","Nacional (sin sede física definida)","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0076","Equipos Monterrey","(Individual) Equipos Monterrey","Norte","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0077","Equipos de Cocina México","(Individual) Equipos de Cocina México","Nacional (sin sede física definida)","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0078","Ferrihogar","(Individual) Ferrihogar","Nacional (sin sede física definida)","Mayorista","Refaccionario"],
  ["UCM-0079","Grupo Alpha Food Service","(Individual) Grupo Alpha Food Service","Nacional (sin sede física definida)","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0080","Hogar y Equipos del Norte","(Individual) Hogar y Equipos del Norte","Norte","Distribuidor","General"],
  ["UCM-0081","Integra Hogar","(Individual) Integra Hogar","Norte","Distribuidor","General"],
  ["UCM-0082","Mayoreo Electromecánico","(Individual) Mayoreo Electromecánico","Occidente","Distribuidor","General"],
  ["UCM-0083","Merco","(Individual) Merco","Norte","Retail / autoservicio","Cadena regional"],
  ["UCM-0084","Mueblería Elizondo","(Individual) Mueblería Elizondo","Norte","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0085","Mueblerías Valdez Baluarte","(Individual) Mueblerías Valdez Baluarte","Noroeste","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0086","Muebles América","(Individual) Muebles América","Occidente","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0087","PCH Mayoreo","(Individual) PCH Mayoreo","Occidente","Mayorista","General"],
  ["UCM-0088","Patlán","(Individual) Patlán","Norte","Distribuidor","General"],
  ["UCM-0089","S-Mart","(Individual) S-Mart","Norte","Retail / autoservicio","Cadena regional"],
  ["UCM-0090","Smart","(Individual) Smart","Norte","Retail / autoservicio","Cadena regional"],
  ["UCM-0091","Super Willys","(Individual) Super Willys","Sureste","Retail / autoservicio","Cadena regional"],
  ["UCM-0092","SuperMayorista","(Individual) SuperMayorista","Centro","Mayorista","General"],
  ["UCM-0093","Zorro Abarrotero","(Individual) Zorro Abarrotero","Centro","Mayorista","Abarrotero"],
  ["UCM-0094","Barper Cocina","","Nacional","Distribuidor","General"],
  ["UCM-0095","Claro Shop","","Nacional","Marketplace / e-commerce","Pure player"],
  ["UCM-0096","Electrodomésticos Baratos CDMX","","Nacional","Distribuidor","General"],
  ["UCM-0097","Ferrepat","","Nacional","Marketplace / e-commerce","General"],
  ["UCM-0098","Linio","","Nacional","Marketplace / e-commerce","Pure player"],
  ["UCM-0099","Sears.com.mx","","Nacional","Marketplace / e-commerce","Híbrido"],
  ["UCM-0100","Superflama","","Nacional","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0101","Marchand","(Individual) Marchand","Centro","Línea blanca / especialista","General"],
  ["UCM-0102","BM Santa Catarina","(Individual) BM Santa Catarina","Centro","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0103","Aká Superbodega","(Individual) Aká Superbodega","Sureste","Retail / autoservicio","Cadena regional"],
  ["UCM-0104","Bodega del Hogar","(Individual) Bodega del Hogar","Nacional (sin sede física definida)","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0105","Casa Díaz Occidente","(Individual) Casa Díaz Occidente","Occidente","Distribuidor","General"],
  ["UCM-0106","Casa Hernández","(Individual) Casa Hernández","Norte","Distribuidor","General"],
  ["UCM-0107","Casa Montes","(Individual) Casa Montes","Centro","Mayorista","General"],
  ["UCM-0108","Comercial Campeche","(Individual) Comercial Campeche","Sureste","Distribuidor","General"],
  ["UCM-0109","Comercial Celaya","(Individual) Comercial Celaya","Bajío","Distribuidor","General"],
  ["UCM-0110","Comercial Irapuato","(Individual) Comercial Irapuato","Bajío","Distribuidor","General"],
  ["UCM-0111","Comercial León","(Individual) Comercial León","Bajío","Distribuidor","General"],
  ["UCM-0112","Comercial Queretana","(Individual) Comercial Queretana","Bajío","Distribuidor","General"],
  ["UCM-0113","Comercial Villahermosa","(Individual) Comercial Villahermosa","Golfo/Sureste","Distribuidor","General"],
  ["UCM-0114","Comercial Zamora","(Individual) Comercial Zamora","Occidente","Distribuidor","General"],
  ["UCM-0115","Comercial de Occidente","(Individual) Comercial de Occidente","Occidente","Distribuidor","General"],
  ["UCM-0116","Comercial del Norte","(Individual) Comercial del Norte","Norte","Distribuidor","General"],
  ["UCM-0117","Cosmos Línea Blanca","(Individual) Cosmos Línea Blanca","Nacional","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0118","Dcocina","(Individual) Dcocina","Centro","Distribuidor","General"],
  ["UCM-0119","Distribuidora Bajío","(Individual) Distribuidora Bajío","Bajío","Distribuidor","General"],
  ["UCM-0120","Distribuidora Colima","(Individual) Distribuidora Colima","Occidente","Distribuidor","General"],
  ["UCM-0121","Distribuidora Peninsular","(Individual) Distribuidora Peninsular","Sureste","Distribuidor","General"],
  ["UCM-0122","Distribuidora Regia","(Individual) Distribuidora Regia","Norte","Distribuidor","General"],
  ["UCM-0123","Distribuidora Salamanca","(Individual) Distribuidora Salamanca","Bajío","Distribuidor","General"],
  ["UCM-0124","Distribuidora Tabasco","(Individual) Distribuidora Tabasco","Golfo/Sureste","Distribuidor","General"],
  ["UCM-0125","Distribuidora Tuxtla","(Individual) Distribuidora Tuxtla","Sureste","Distribuidor","General"],
  ["UCM-0126","EPS Electro-Partes","(Individual) EPS Electro-Partes","Noroeste","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0127","El Florido","(Individual) El Florido","Noroeste","Retail / autoservicio","Cadena regional"],
  ["UCM-0128","Euroelectrica","(Individual) Euroelectrica","Nacional (sin sede física definida)","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0129","Exel del Norte","(Individual) Exel del Norte","Norte","Mayorista","General"],
  ["UCM-0130","Famsa","(Individual) Famsa","Norte","Retail / autoservicio","Departamental"],
  ["UCM-0131","Fantasías Miguel","(Individual) Fantasías Miguel","Centro","Línea blanca / especialista","General"],
  ["UCM-0132","Foly Muebles","(Individual) Foly Muebles","Norte","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0133","Garcés","(Individual) Garcés","Sur","Retail / autoservicio","Cadena regional"],
  ["UCM-0134","Grupo Cancún Comercial","(Individual) Grupo Cancún Comercial","Sureste","Distribuidor","General"],
  ["UCM-0135","Grupo Chiapas Comercial","(Individual) Grupo Chiapas Comercial","Sureste","Distribuidor","General"],
  ["UCM-0136","Grupo Cozumel","(Individual) Grupo Cozumel","Sureste","Distribuidor","General"],
  ["UCM-0137","Grupo Gonher","(Individual) Grupo Gonher","Norte","Distribuidor","Regional"],
  ["UCM-0138","Grupo Logístico Potosino","(Individual) Grupo Logístico Potosino","Bajío","Distribuidor","Logístico"],
  ["UCM-0139","Grupo Mérida Hogar","(Individual) Grupo Mérida Hogar","Sureste","Distribuidor","General"],
  ["UCM-0140","Grupo QP","(Individual) Grupo QP","Occidente","Distribuidor","General"],
  ["UCM-0141","Grupo Vallarta","(Individual) Grupo Vallarta","Occidente","Distribuidor","Regional"],
  ["UCM-0142","Grupo Vega","(Individual) Grupo Vega","Bajío","Distribuidor","General"],
  ["UCM-0143","Kitchen Market","(Individual) Kitchen Market","Centro","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0144","La Marina","(Individual) La Marina","Golfo/Sureste","Retail / autoservicio","General"],
  ["UCM-0145","MAHA","(Individual) MAHA","Norte","Mayorista","General"],
  ["UCM-0146","Mayoreo Cárdenas","(Individual) Mayoreo Cárdenas","Occidente","Distribuidor","General"],
  ["UCM-0147","Mueblería Standard","(Individual) Mueblería Standard","Nacional (sin sede física definida)","Distribuidor","General"],
  ["UCM-0148","Muebles Dico Occidente","(Individual) Muebles Dico Occidente","Occidente","Línea blanca / especialista","Mueblería"],
  ["UCM-0150","Rational México","(Individual) Rational México","Centro","Línea blanca / especialista","General"],
  ["UCM-0151","Riviera Distribución","(Individual) Riviera Distribución","Sureste","Distribuidor","General"],
  ["UCM-0152","Rosan Internacional","(Individual) Rosan Internacional","Centro","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0153","Tiendas Garcés","(Individual) Tiendas Garcés","Sur","Retail / autoservicio","Cadena regional"],
  ["UCM-0154","Truper Expert","(Individual) Truper Expert","Centro","Línea blanca / especialista","General"],
  ["UCM-0155","Vianney Hogar","(Individual) Vianney Hogar","Bajío","Línea blanca / especialista","General"],
  ["UCM-0156","Alsuper Store","","Nacional","Retail / autoservicio","Cadena regional"],
  ["UCM-0157","Casa Marchand","","Nacional","Retail / autoservicio","Cadena regional"],
  ["UCM-0158","Hamilton Beach México","","Nacional","Marca / fabricante","General"],
  ["UCM-0159","Oster México / Newell","","Nacional","Marca / fabricante","General"],
  ["UCM-0160","Tiendas Neto","","Nacional","Retail / autoservicio","Cadena regional"],
  ["UCM-0161","Turmix de México","","Nacional","Marca / fabricante","General"],
  ["UCM-0162","Grupo Ascencio / DEASA","","Occidente","Distribuidor","General"],
  ["UCM-0163","Electrodomésticos Olvera Madero Pte","","Norte","Retail / autoservicio","General"],
  ["UCM-0164","Waldos Dollar Mart","Waldos Dollar Mart de México","Nacional","Línea blanca / especialista","General"],
  ["UCM-0165","Ryse Delta","","Bajío","Retail / autoservicio","General"],
  ["UCM-0166","Office Depot México","Office Depot de México","Nacional","Línea blanca / especialista","General"],
  ["UCM-0167","Sam's Club México","Walmart de México (Walmex)","Nacional","Retail / autoservicio","Club de precios"],
  ["UCM-0168","Tiendas Atlas","(Individual) Tiendas Atlas","Nacional","Línea blanca / especialista","Mueblería"],
  ["UCM-0169","El Bodegón","","Occidente","Retail / autoservicio","General"],
  ["UCM-0170","OfficeMax México","Operadora OMX (OfficeMax México)","Nacional","Línea blanca / especialista","General"],
  ["UCM-0171","Mayoreo Libre","","Centro","Mayorista","General"],
  ["UCM-0172","City Club","Organización Soriana (City Club)","Nacional","Retail / autoservicio","General"],
  ["UCM-0173","Anforama","Comercial Anforama","Nacional","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0174","Radio Shack México","Grupo Gigante (RadioShack)","Nacional","Línea blanca / especialista","General"],
  ["UCM-0175","Smart & Final del Noroeste","Smart & Final del Noroeste (JV Chedraui/Calimax)","Noroeste","Mayorista","General"],
  ["UCM-0176","Cimaco","Cía. Comercial Cimaco","Norte","Retail / autoservicio","Departamental"],
  ["UCM-0177","Electrodomésticos Olvera","(Individual) Electrodomésticos Olvera Matriz","Norte","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0178","Tiendas Chapur","(Individual) Tiendas Chapur","Sureste","Retail / autoservicio","Departamental"],
  ["UCM-0179","La Proveedora del Hogar / PDH","(Individual) La Proveedora del Hogar / PDH","Centro","Línea blanca / especialista","General"],
  ["UCM-0180","CDO","","Centro","Distribuidor","General"],
  ["UCM-0181","Todo por Mayoreo","","Nacional","Mayorista","General"],
  ["UCM-0182","19 Hermanos","(Individual) 19 Hermanos","Occidente","Mayorista","Abarrotero"],
  ["UCM-0183","Abarrotera Fuentes","(Individual) Abarrotera Fuentes","Centro","Mayorista","Abarrotero"],
  ["UCM-0184","Abarrotes La Violeta","(Individual) Abarrotes La Violeta","Occidente","Mayorista","Abarrotero"],
  ["UCM-0185","Abastecedora Comercial de Parral","(Individual) Abastecedora Comercial de Parral","Norte","Mayorista","Abarrotero"],
  ["UCM-0186","Abasteo","(Individual) Abasteo","Nacional","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0187","Almacenes Anfora","(Individual) Almacenes Anfora","Nacional","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0188","Almacenes García","(Individual) Almacenes García","Nacional","Retail / autoservicio","Departamental"],
  ["UCM-0189","Aluz","(Individual) Aluz","Norte","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0190","Casa Lupita","(Individual) Casa Lupita","Occidente","Mayorista","Abarrotero"],
  ["UCM-0191","Centro Comercial Cruz Azul","(Individual) Centro Comercial Cruz Azul","Centro","Retail / autoservicio","General"],
  ["UCM-0192","Chef Market","(Individual) Chef Market","Centro","Mayorista","General"],
  ["UCM-0193","Cocinas y Equipamientos B&P","(Individual) Cocinas y Equipamientos B&P","Occidente","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0194","Comercial Balandra","(Individual) Comercial Balandra","Noroeste","Retail / autoservicio","General"],
  ["UCM-0195","Comercial San Luis","(Individual) Comercial San Luis","Bajío","Retail / autoservicio","General"],
  ["UCM-0196","Comercial Treviño","(Individual) Comercial Treviño","Norte","Mayorista","Abarrotero"],
  ["UCM-0197","Comercializadora JM","(Individual) Comercializadora JM","Norte","Mayorista","Abarrotero"],
  ["UCM-0198","Cosaltor","(Individual) Cosaltor","Centro","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0199","Damsa / La Mixteca","(Individual) Damsa / La Mixteca","Centro","Mayorista","Abarrotero"],
  ["UCM-0200","Decasa","(Individual) Decasa","Bajío","Mayorista","Abarrotero"],
  ["UCM-0201","Disroga","(Individual) Disroga","Centro","Mayorista","Abarrotero"],
  ["UCM-0202","Distribuidora Hugos","(Individual) Distribuidora Hugos","Occidente","Mayorista","Abarrotero"],
  ["UCM-0203","El Nuevo Mundo","(Individual) El Nuevo Mundo","Centro","Retail / autoservicio","Departamental"],
  ["UCM-0204","El Rey de Corregidora","(Individual) El Rey de Corregidora","Centro","Mayorista","General"],
  ["UCM-0205","Expansión DI","(Individual) Expansión DI","Centro","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0206","Fénix El Super de Casa","(Individual) Fénix El Super de Casa","Golfo/Sureste","Retail / autoservicio","General"],
  ["UCM-0207","Grupo Casa Rodríguez","(Individual) Grupo Casa Rodríguez","Centro","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0208","Grupo Cevisa","(Individual) Grupo Cevisa","Centro","Mayorista","General"],
  ["UCM-0209","Grupo Venegas","(Individual) Grupo Venegas","Norte","Mayorista","Abarrotero"],
  ["UCM-0210","HG Avante","(Individual) HG Avante","Golfo/Sureste","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0211","Hemsa","(Individual) Hemsa","Norte","Retail / autoservicio","Departamental"],
  ["UCM-0212","La Misión Supermercados","(Individual) La Misión Supermercados","Noroeste","Retail / autoservicio","General"],
  ["UCM-0213","Línea Blanca Giil","(Individual) Línea Blanca Giil","Centro","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0214","Maz Zumpango","(Individual) Maz Zumpango","Centro","Mayorista","Abarrotero"],
  ["UCM-0215","Mercado Mayco","(Individual) Mercado Mayco","Norte","Mayorista","Abarrotero"],
  ["UCM-0216","Mercantil del Hogar","(Individual) Mercantil del Hogar","Centro","Mayorista","Refaccionario"],
  ["UCM-0217","Multimarcas del Bajío","(Individual) Multimarcas del Bajío","Bajío","Mayorista","General"],
  ["UCM-0218","Más Bodega y Logística","(Individual) Más Bodega y Logística","Noroeste","Retail / autoservicio","General"],
  ["UCM-0219","Nieto Comercial","(Individual) Nieto Comercial","Centro","Mayorista","Abarrotero"],
  ["UCM-0220","Ofix","(Individual) Ofix","Nacional","Línea blanca / especialista","General"],
  ["UCM-0221","Organización CIR","(Individual) Organización CIR","Occidente","Mayorista","Abarrotero"],
  ["UCM-0222","PDH Puebla","(Individual) PDH Puebla","Centro","Retail / autoservicio","General"],
  ["UCM-0223","PDH Veracruz","(Individual) PDH Veracruz","Golfo/Sureste","Retail / autoservicio","General"],
  ["UCM-0224","Piticó","(Individual) Piticó","Sureste","Retail / autoservicio","General"],
  ["UCM-0225","Productos Básicos de Córdoba","(Individual) Productos Básicos de Córdoba","Golfo/Sureste","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0226","Proper Services","(Individual) Proper Services","Centro","Mayorista","General"],
  ["UCM-0227","Proveedora Diez","(Individual) Proveedora Diez","Centro","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0228","RG Audio y Video","(Individual) RG Audio y Video","Centro","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0229","Ryse","(Individual) Ryse","Bajío","Mayorista","Refaccionario"],
  ["UCM-0230","Satus Inteligencia Comercial","(Individual) Satus Inteligencia Comercial","Centro","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0231","Steren","(Individual) Steren","Nacional","Línea blanca / especialista","General"],
  ["UCM-0232","Su Bodega","(Individual) Su Bodega","Golfo/Sureste","Retail / autoservicio","General"],
  ["UCM-0233","Su Plaza","(Individual) Su Plaza","Centro","Retail / autoservicio","General"],
  ["UCM-0234","Supermercados Aramburo","(Individual) Supermercados Aramburo","Noroeste","Retail / autoservicio","General"],
  ["UCM-0235","Surtiloza","(Individual) Surtiloza","Occidente","Línea blanca / especialista","Cocina / HORECA"],
  ["UCM-0236","Súper Gutiérrez","(Individual) Súper Gutiérrez","Norte","Retail / autoservicio","General"],
  ["UCM-0237","Súper San Francisco de Asís","(Individual) Súper San Francisco de Asís","Sureste","Retail / autoservicio","General"],
  ["UCM-0238","The Home Store","(Individual) The Home Store","Nacional","Línea blanca / especialista","General"],
  ["UCM-0239","El Bodegón Colima Centro","","Occidente","Retail / autoservicio","General"],
  ["UCM-0240","Electrodomésticos Olvera Chihuahua","","Norte","Retail / autoservicio","General"],
  ["UCM-0241","Electrodomésticos Olvera Matriz","","Norte","Línea blanca / especialista","Electrodomésticos"],
  ["UCM-0242","Electrodomésticos Olvera Reynosa","","Norte","Retail / autoservicio","General"],
  ["UCM-0243","Electrodomésticos Olvera Saltillo","","Norte","Retail / autoservicio","General"],
  ["UCM-0244","Global Office / Distribuidor Oster Guadalajara","","Occidente","Distribuidor","Exclusivo Turmix"],
  ["UCM-0245","Grupo Ascencio / AIESA","","Occidente","Distribuidor","General"],
  ["UCM-0246","Jugomex / Comercializadora Berista","","Centro","Distribuidor","General"],
  ["UCM-0247","Proveedora del Hogar / proveedoradelhogar.com.mx","","Centro","Mayorista","General"],
  ["UCM-0248","Saesa Trading","","Centro","Distribuidor","General"],
].map(([id, name, group, territory, channel, subchannel]) => ({ id, name, group, territory, channel, subchannel })) as readonly AlfaUniverseAccount[];
