export type AlfaUniverseAccount = { id: string; name: string; group: string; territory: string; channel: string; subchannel: string };

// Catálogo comercial canónico: 199 cuentas del universo maestro de Revenue.
// La data transaccional es sintética; las dimensiones no se inventan.
export const ALFA_UNIVERSE_ACCOUNTS: readonly AlfaUniverseAccount[] = [
  ["UMX-156", "Elektra", "Grupo Elektra / Grupo Salinas", "Centro", "Retail Credito", "Electrónica/crédito popular"],
  ["UMX-158", "Bodega Aurrera", "Walmart de México (Walmex)", "Centro", "Retail Moderno", "Autoservicio popular"],
  ["UMX-007", "Coppel", "Grupo Coppel", "Noroeste", "Departamental", "Departamental/crédito popular"],
  ["UMX-175", "Neto", "Tiendas Neto (Grupo Salinas via Banco Azteca? validar)", "Centro", "Retail Nacional", "Autoservicio popular"],
  ["UMX-204", "Waldos Dollar Mart", "Waldos Dollar Mart de México", "Nacional", "Especialistas", "Variedades / precio bajo"],
  ["UMX-165", "Soriana", "Organización Soriana", "Norte", "Retail Moderno", "Autoservicio"],
  ["UMX-172", "Dunosusa", "Dunosusa (Proveedora del Panadero)", "Sureste", "Retail Regional", "Autoservicio regional"],
  ["UMX-161", "Walmart México", "Walmart de México (Walmex)", "Centro", "Retail Moderno", "Autoservicio"],
  ["UMX-167", "Casa Ley", "Casa Ley (familia Ley / Albertsons 49%)", "Noroeste", "Retail Regional", "Autoservicio regional"],
  ["UMX-213", "Office Depot México", "Office Depot de México", "Nacional", "Especialistas", "Oficina / ecommerce"],
  ["UMX-162", "Chedraui", "Grupo Comercial Chedraui", "Golfo/Sureste", "Retail Moderno", "Autoservicio"],
  ["UMX-013", "Suburbia", "El Puerto de Liverpool", "Centro", "Departamental", "Departamental popular"],
  ["UMX-006", "Sam's Club México", "Walmart de México (Walmex)", "Nacional", "Clubes de Precio", "Electrodomésticos de cocina, línea blanca"],
  ["UMX-105", "Home Depot", "The Home Depot México", "Norte", "Home Improvement", "Home improvement"],
  ["UMX-148", "Grupo Roga", "Grupo Roga (Villarreal Muebles / El Pasito)", "Norte", "Mueblerias", "Muebles/electrodomésticos"],
  ["UMX-219", "Tiendas Atlas", "(Individual) Tiendas Atlas", "Nacional", "Mueblerias", "Hogar / muebles"],
  ["UMX-157", "El Bodegón Crédito", "(Individual) El Bodegón Crédito", "Bajío", "Retail Credito", "Crédito regional"],
  ["UMX-012", "Sanborns", "Grupo Sanborns / Grupo Carso", "Centro", "Departamental", "Tienda departamental/restaurante"],
  ["UMX-010", "Del Sol", "Grupo Comercial Control (Del Sol / Woolworth)", "Norte", "Departamental", "Departamental popular"],
  ["UMX-008", "Liverpool", "El Puerto de Liverpool", "Centro", "Departamental", "Departamental nacional"],
  ["UMX-216", "Radio Shack México", "Grupo Gigante (RadioShack)", "Nacional", "Especialistas", "Electrónica"],
  ["UMX-171", "Calimax", "Calimax (Grupo Calimax)", "Noroeste", "Retail Regional", "Autoservicio regional"],
  ["UMX-009", "Sears México", "Grupo Sanborns / Grupo Carso", "Centro", "Departamental", "Departamental nacional"],
  ["UMX-214", "OfficeMax México", "Operadora OMX (OfficeMax México)", "Nacional", "Especialistas", "Oficina / ecommerce"],
  ["UMX-168", "HEB México", "H-E-B México", "Norte", "Retail Regional", "Autoservicio regional"],
  ["UMX-169", "Alsuper", "Grupo Futurama (Alsuper / S-Mart / Fresh Market)", "Norte", "Retail Regional", "Autoservicio regional"],
  ["UMX-131", "CT Internacional", "(Individual) CT Internacional", "Noroeste", "Mayoreo", "Tecnología / electrónica"],
  ["UMX-004", "Costco México", "Costco Wholesale México", "Centro", "Clubes de Precio", "Club mayorista"],
  ["UMX-005", "City Club", "Organización Soriana (City Club)", "Nacional", "Clubes de Precio", "Electrodomésticos al mayoreo"],
  ["UMX-091", "Marchand", "(Individual) Marchand", "Centro", "Especialistas", "Papelería/hogar"],
  ["UMX-166", "La Comer", "Grupo La Comer", "Centro", "Retail Moderno", "Autoservicio / Premium"],
  ["UMX-212", "Anforama", "Comercial Anforama", "Nacional", "Especialistas", "Hogar / cocina"],
  ["UMX-164", "Fresko", "Grupo La Comer", "Centro", "Retail Moderno", "Autoservicio / Premium"],
  ["UMX-163", "City Market", "Grupo La Comer", "Centro", "Retail Moderno", "Autoservicio / Premium"],
  ["UMX-011", "El Palacio de Hierro", "Grupo Palacio de Hierro", "Centro", "Departamental", "Departamental premium"],
  ["UMX-103", "Sodimac México", "Sodimac / Falabella (operado vía Soriana)", "Centro", "Home Improvement", "Mejoras para el hogar"],
  ["UMX-205", "Smart & Final del Noroeste", "Smart & Final del Noroeste (JV Chedraui/Calimax)", "Noroeste", "Mayoreo", "Mayoreo autoservicio"],
  ["UMX-160", "Super Che", "Grupo Comercial Chedraui", "Golfo/Sureste", "Retail Moderno", "Autoservicio"],
  ["UMX-015", "Grupo Encanto", "(Individual) Grupo Encanto", "Norte", "Distribuidores", "Distribuidor nacional/regional"],
  ["UMX-207", "Cimaco", "Cía. Comercial Cimaco", "Norte", "Departamental", "Departamental"],
  ["UMX-210", "Tiendas Chapur", "(Individual) Tiendas Chapur", "Sureste", "Departamental", "Departamental"],
  ["UMX-121", "La Proveedora del Hogar / PDH", "(Individual) La Proveedora del Hogar / PDH", "Centro", "Horeca", "Licuadoras, extractores, cafeteras, negocio/restaurante"],
  ["UMX-126", "PDH Domésticos", "(Individual) PDH Domésticos", "Centro", "Mayoreo", "Electrodomésticos / cocina"],
  ["UMX-152", "BM Santa Catarina", "(Individual) BM Santa Catarina", "Centro", "Mueblerias", "Línea blanca, muebles"],
  ["UMX-173", "Mega Outlet Fernández", "(Individual) Mega Outlet Fernández", "Centro", "Retail Regional", "Outlet / línea blanca"],
  ["UMX-002", "Abasteo", "(Individual) Abasteo", "Nacional", "B2B", "Batidoras, cafeteras, electrodomésticos para empresa"],
  ["UMX-244", "Aluz", "(Individual) Aluz", "Norte", "B2B", "Línea blanca"],
  ["UMX-238", "Cocinas y Equipamientos B&P", "(Individual) Cocinas y Equipamientos B&P", "Occidente", "B2B", "Línea blanca / equipamiento"],
  ["UMX-236", "Cosaltor", "(Individual) Cosaltor", "Centro", "B2B", "Línea blanca"],
  ["UMX-001", "Cosmos Línea Blanca", "(Individual) Cosmos Línea Blanca", "Nacional", "B2B", "Línea blanca; cotizaciones"],
  ["UMX-239", "Expansión DI", "(Individual) Expansión DI", "Centro", "B2B", "Línea blanca"],
  ["UMX-240", "HG Avante", "(Individual) HG Avante", "Golfo/Sureste", "B2B", "Línea blanca"],
  ["UMX-241", "Línea Blanca Giil", "(Individual) Línea Blanca Giil", "Centro", "B2B", "Línea blanca"],
  ["UMX-242", "Productos Básicos de Córdoba", "(Individual) Productos Básicos de Córdoba", "Golfo/Sureste", "B2B", "Línea blanca"],
  ["UMX-243", "RG Audio y Video", "(Individual) RG Audio y Video", "Centro", "B2B", "Línea blanca / electrónica"],
  ["UMX-237", "Satus Inteligencia Comercial", "(Individual) Satus Inteligencia Comercial", "Centro", "B2B", "Línea blanca"],
  ["UMX-003", "Surtiloza", "(Individual) Surtiloza", "Occidente", "B2B", "Cocina profesional y hogar"],
  ["UMX-206", "Almacenes García", "(Individual) Almacenes García", "Nacional", "Departamental", "Departamental"],
  ["UMX-208", "El Nuevo Mundo", "(Individual) El Nuevo Mundo", "Centro", "Departamental", "Departamental"],
  ["UMX-014", "Famsa", "(Individual) Famsa", "Norte", "Departamental", "Muebles/electrodomésticos"],
  ["UMX-209", "Hemsa", "(Individual) Hemsa", "Norte", "Departamental", "Departamental"],
  ["UMX-020", "Alkia", "(Individual) Alkia", "Bajío", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-016", "Boxito", "(Individual) Boxito", "Sureste", "Distribuidores", "Construcción/hogar"],
  ["UMX-027", "Casa Díaz Occidente", "(Individual) Casa Díaz Occidente", "Occidente", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-028", "Casa Hernández", "(Individual) Casa Hernández", "Norte", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-029", "Comercial Campeche", "(Individual) Comercial Campeche", "Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-030", "Comercial Celaya", "(Individual) Comercial Celaya", "Bajío", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-031", "Comercial Irapuato", "(Individual) Comercial Irapuato", "Bajío", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-032", "Comercial León", "(Individual) Comercial León", "Bajío", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-033", "Comercial Queretana", "(Individual) Comercial Queretana", "Bajío", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-034", "Comercial Villahermosa", "(Individual) Comercial Villahermosa", "Golfo/Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-035", "Comercial Zamora", "(Individual) Comercial Zamora", "Occidente", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-036", "Comercial de Occidente", "(Individual) Comercial de Occidente", "Occidente", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-037", "Comercial del Norte", "(Individual) Comercial del Norte", "Norte", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-025", "Dcocina", "(Individual) Dcocina", "Centro", "Distribuidores", "Utensilios, cocina hogar"],
  ["UMX-038", "Distribuidora Bajío", "(Individual) Distribuidora Bajío", "Bajío", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-039", "Distribuidora Colima", "(Individual) Distribuidora Colima", "Occidente", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-040", "Distribuidora Peninsular", "(Individual) Distribuidora Peninsular", "Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-041", "Distribuidora Regia", "(Individual) Distribuidora Regia", "Norte", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-042", "Distribuidora Salamanca", "(Individual) Distribuidora Salamanca", "Bajío", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-043", "Distribuidora Tabasco", "(Individual) Distribuidora Tabasco", "Golfo/Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-044", "Distribuidora Tuxtla", "(Individual) Distribuidora Tuxtla", "Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-017", "Grupo Ascencio", "(Individual) Grupo Ascencio", "Occidente", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-047", "Grupo Cancún Comercial", "(Individual) Grupo Cancún Comercial", "Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-048", "Grupo Chiapas Comercial", "(Individual) Grupo Chiapas Comercial", "Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-049", "Grupo Cozumel", "(Individual) Grupo Cozumel", "Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-050", "Grupo Gonher", "(Individual) Grupo Gonher", "Norte", "Distribuidores", "Autopartes/retail regional"],
  ["UMX-051", "Grupo Logístico Potosino", "(Individual) Grupo Logístico Potosino", "Bajío", "Distribuidores", "Logística/comercial"],
  ["UMX-052", "Grupo Mérida Hogar", "(Individual) Grupo Mérida Hogar", "Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-053", "Grupo QP", "(Individual) Grupo QP", "Occidente", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-054", "Grupo Vallarta", "(Individual) Grupo Vallarta", "Occidente", "Distribuidores", "Retail/regional"],
  ["UMX-055", "Grupo Vega", "(Individual) Grupo Vega", "Bajío", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-021", "Hogar y Equipos del Norte", "(Individual) Hogar y Equipos del Norte", "Norte", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-022", "Integra Hogar", "(Individual) Integra Hogar", "Norte", "Distribuidores", "Distribuidor / showroom"],
  ["UMX-026", "Mayoreo Cárdenas", "(Individual) Mayoreo Cárdenas", "Occidente", "Distribuidores", "Canal ferretero/hogar"],
  ["UMX-023", "Mayoreo Electromecánico", "(Individual) Mayoreo Electromecánico", "Occidente", "Distribuidores", "Refacciones / servicio"],
  ["UMX-057", "Mueblería Standard", "(Individual) Mueblería Standard", "Nacional (sin sede física definida)", "Distribuidores", "Hogar / muebles / línea blanca"],
  ["UMX-024", "Patlán", "(Individual) Patlán", "Norte", "Distribuidores", "Tienda / distribución"],
  ["UMX-058", "Riviera Distribución", "(Individual) Riviera Distribución", "Sureste", "Distribuidores", "Hogar/electrodomésticos"],
  ["UMX-019", "Veana", "(Individual) Veana", "Nacional (sin sede física definida)", "Distribuidores", "Retail regional"],
  ["UMX-018", "Xaze", "(Individual) Xaze", "Centro", "Distribuidores", "Electrónica / hogar"],
  ["UMX-077", "Aguilar Refacciones", "(Individual) Aguilar Refacciones", "Nacional (sin sede física definida)", "Especialistas", "Refacciones electrodomésticos"],
  ["UMX-211", "Almacenes Anfora", "(Individual) Almacenes Anfora", "Nacional", "Especialistas", "Hogar / cocina"],
  ["UMX-082", "Bodega del Hogar", "(Individual) Bodega del Hogar", "Nacional (sin sede física definida)", "Especialistas", "Hogar/electrodomésticos"],
  ["UMX-078", "Casa Cravioto", "(Individual) Casa Cravioto", "Centro", "Especialistas", "Ferretería / hogar"],
  ["UMX-080", "EPS Electro-Partes", "(Individual) EPS Electro-Partes", "Noroeste", "Especialistas", "Refacciones línea blanca/electrodomésticos"],
  ["UMX-085", "Electrodomésticos Olvera", "(Individual) Electrodomésticos Olvera Matriz", "Norte", "Especialistas", "Refacciones licuadora, electrodomésticos, equipo industrial"],
  ["UMX-079", "Electros para Casa", "(Individual) Electros para Casa", "Nacional (sin sede física definida)", "Especialistas", "Cocinas/equipos"],
  ["UMX-088", "Euroelectrica", "(Individual) Euroelectrica", "Nacional (sin sede física definida)", "Especialistas", "Electrodomésticos/línea blanca"],
  ["UMX-089", "Fantasías Miguel", "(Individual) Fantasías Miguel", "Centro", "Especialistas", "Manualidades/hogar"],
  ["UMX-090", "Kitchen Market", "(Individual) Kitchen Market", "Centro", "Especialistas", "Cocina"],
  ["UMX-215", "Ofix", "(Individual) Ofix", "Nacional", "Especialistas", "Oficina / ecommerce"],
  ["UMX-081", "Rosan Internacional", "(Individual) Rosan Internacional", "Centro", "Especialistas", "Refacciones licuadora/electrodomésticos"],
  ["UMX-217", "Steren", "(Individual) Steren", "Nacional", "Especialistas", "Electrónica"],
  ["UMX-218", "The Home Store", "(Individual) The Home Store", "Nacional", "Especialistas", "Hogar"],
  ["UMX-092", "Truper Expert", "(Individual) Truper Expert", "Centro", "Especialistas", "Ferretería"],
  ["UMX-093", "Vianney Hogar", "(Individual) Vianney Hogar", "Bajío", "Especialistas", "Hogar/textil"],
  ["UMX-114", "Berista", "(Individual) Berista", "Centro", "Horeca", "Café / foodservice"],
  ["UMX-115", "Central de Cocinas Industriales", "(Individual) Central de Cocinas Industriales", "Nacional (sin sede física definida)", "Horeca", "Cocinas industriales"],
  ["UMX-116", "Cocinas Institucionales", "(Individual) Cocinas Institucionales", "Nacional (sin sede física definida)", "Horeca", "Cocinas industriales"],
  ["UMX-117", "Equipos Monterrey", "(Individual) Equipos Monterrey", "Norte", "Horeca", "Equipo cocina/foodservice"],
  ["UMX-118", "Equipos de Cocina México", "(Individual) Equipos de Cocina México", "Nacional (sin sede física definida)", "Horeca", "Cocinas industriales"],
  ["UMX-119", "Grupo Alpha Food Service", "(Individual) Grupo Alpha Food Service", "Nacional (sin sede física definida)", "Horeca", "Foodservice"],
  ["UMX-120", "Grupo Casa Rodríguez", "(Individual) Grupo Casa Rodríguez", "Centro", "Horeca", "Equipamiento cocina, utensilios, horeca"],
  ["UMX-107", "Inmeza", "(Individual) Inmeza", "Occidente", "Horeca", "Cocinas industriales"],
  ["UMX-108", "Jugomex", "(Individual) Jugomex", "Centro", "Horeca", "Equipamiento juguerías / foodservice"],
  ["UMX-109", "Migsa", "(Individual) Migsa", "Centro", "Horeca", "Cocinas industriales"],
  ["UMX-110", "PiquioMart", "(Individual) PiquioMart", "Centro", "Horeca", "Mayorista / food service"],
  ["UMX-122", "Proveedora Diez", "(Individual) Proveedora Diez", "Centro", "Horeca", "Cocina profesional, cafeterías, restaurantes"],
  ["UMX-124", "Rational México", "(Individual) Rational México", "Centro", "Horeca", "Equipo profesional"],
  ["UMX-112", "Torrey Distribución", "(Individual) Torrey Distribución", "Norte", "Horeca", "Equipo comercial/cocina"],
  ["UMX-113", "Zona Chef", "(Individual) Zona Chef", "Nacional (sin sede física definida)", "Horeca", "Equipamiento gastronómico"],
  ["UMX-228", "19 Hermanos", "(Individual) 19 Hermanos", "Occidente", "Mayoreo", "Mayorista abarrotero"],
  ["UMX-231", "Abarrotera Fuentes", "(Individual) Abarrotera Fuentes", "Centro", "Mayoreo", "Mayorista abarrotero"],
  ["UMX-229", "Abarrotes La Violeta", "(Individual) Abarrotes La Violeta", "Occidente", "Mayoreo", "Mayorista abarrotero"],
  ["UMX-220", "Abastecedora Comercial de Parral", "(Individual) Abastecedora Comercial de Parral", "Norte", "Mayoreo", "Mayorista abarrotero"],
  ["UMX-132", "CVA Mayoreo", "(Individual) CVA Mayoreo", "Occidente", "Mayoreo", "Tecnología / electrónica"],
  ["UMX-125", "Casa Ahued", "(Individual) Casa Ahued", "Golfo/Sureste", "Mayoreo", "Hogar / cocina / electrodomésticos"],
  ["UMX-230", "Casa Lupita", "(Individual) Casa Lupita", "Occidente", "Mayoreo", "Mayorista abarrotero"],
  ["UMX-133", "Casa Marcus", "(Individual) Casa Marcus", "Centro", "Mayoreo", "Mayorista / tienda centro"],
  ["UMX-138", "Casa Montes", "(Individual) Casa Montes", "Centro", "Mayoreo", "Artículos de cocina; posible complemento electrodoméstico"],
  ["UMX-127", "Central Distribuidora Ojeda", "(Individual) Central Distribuidora Ojeda", "Nacional (sin sede física definida)", "Mayoreo", "Distribuidor / B2B"],
  ["UMX-140", "Chef Market", "(Individual) Chef Market", "Centro", "Mayoreo", "Cocina, hogar, electrodomésticos"],
  ["UMX-235", "Comercial Treviño", "(Individual) Comercial Treviño", "Norte", "Mayoreo", "Mayorista abarrotero"],
  ["UMX-234", "Comercializadora JM", "(Individual) Comercializadora JM", "Norte", "Mayoreo", "Mayorista abarrotero"],
  ["UMX-224", "Damsa / La Mixteca", "(Individual) Damsa / La Mixteca", "Centro", "Mayoreo", "Mayorista abarrotero"],
  ["UMX-226", "Decasa", "(Individual) Decasa", "Bajío", "Mayoreo", "Mayorista abarrotero"],
  ["UMX-128", "Dicom2000", "(Individual) Dicom2000", "Nacional (sin sede física definida)", "Mayoreo", "Mayorista nacional"],
  ["UMX-223", "Disroga", "(Individual) Disroga", "Centro", "Mayoreo", "Mayorista abarrotero"],
  ["UMX-227", "Distribuidora Hugos", "(Individual) Distribuidora Hugos", "Occidente", "Mayoreo", "Mayorista abarrotero"],
  ["UMX-141", "El Rey de Corregidora", "(Individual) El Rey de Corregidora", "Centro", "Mayoreo", "Enseres menores, licuadoras, cafeteras, hornos, electrónica"],
  ["UMX-129", "Electroking", "(Individual) Electroking", "Centro", "Mayoreo", "Línea blanca / electrodomésticos"],
  ["UMX-142", "Exel del Norte", "(Individual) Exel del Norte", "Norte", "Mayoreo", "Tecnología/electrónica"],
  ["UMX-134", "Ferrihogar", "(Individual) Ferrihogar", "Nacional (sin sede física definida)", "Mayoreo", "Refacciones / mayoreo"],
  ["UMX-143", "Grupo Cevisa", "(Individual) Grupo Cevisa", "Centro", "Mayoreo", "Línea blanca, muebles, electrónica, electrodomésticos"],
  ["UMX-222", "Grupo Venegas", "(Individual) Grupo Venegas", "Norte", "Mayoreo", "Mayorista abarrotero"],
  ["UMX-139", "MAHA", "(Individual) MAHA", "Norte", "Mayoreo", "Artículos de cocina precio mayoreo"],
  ["UMX-225", "Maz Zumpango", "(Individual) Maz Zumpango", "Centro", "Mayoreo", "Mayorista abarrotero"],
  ["UMX-221", "Mercado Mayco", "(Individual) Mercado Mayco", "Norte", "Mayoreo", "Mayorista abarrotero"],
  ["UMX-144", "Mercantil del Hogar", "(Individual) Mercantil del Hogar", "Centro", "Mayoreo", "Licuadoras, refacciones, cafeteras, ollas, estufas"],
  ["UMX-130", "Merza", "(Individual) Merza", "Occidente", "Mayoreo", "Autoservicio / mayoreo regional"],
  ["UMX-145", "Multimarcas del Bajío", "(Individual) Multimarcas del Bajío", "Bajío", "Mayoreo", "Enseres menores y línea blanca"],
  ["UMX-232", "Nieto Comercial", "(Individual) Nieto Comercial", "Centro", "Mayoreo", "Mayorista abarrotero"],
  ["UMX-233", "Organización CIR", "(Individual) Organización CIR", "Occidente", "Mayoreo", "Mayorista abarrotero"],
  ["UMX-135", "PCH Mayoreo", "(Individual) PCH Mayoreo", "Occidente", "Mayoreo", "Tecnología / electrónica"],
  ["UMX-146", "Proper Services", "(Individual) Proper Services", "Centro", "Mayoreo", "Licuadoras, extractores, cafeteras, línea blanca, incentivos"],
  ["UMX-147", "Ryse", "(Individual) Ryse", "Bajío", "Mayoreo", "Enseres menores, línea blanca, refacciones, comercial"],
  ["UMX-136", "SuperMayorista", "(Individual) SuperMayorista", "Centro", "Mayoreo", "Mayoreo digital"],
  ["UMX-137", "Zorro Abarrotero", "(Individual) Zorro Abarrotero", "Centro", "Mayoreo", "Abarrotero mayorista"],
  ["UMX-153", "Foly Muebles", "(Individual) Foly Muebles", "Norte", "Mueblerias", "Línea blanca; electrodomésticos menor no confirmado"],
  ["UMX-149", "Mueblería Elizondo", "(Individual) Mueblería Elizondo", "Norte", "Mueblerias", "Muebles/electrodomésticos"],
  ["UMX-150", "Mueblerías Valdez Baluarte", "(Individual) Mueblerías Valdez Baluarte", "Noroeste", "Mueblerias", "Muebles/electrodomésticos"],
  ["UMX-151", "Muebles América", "(Individual) Muebles América", "Occidente", "Mueblerias", "Muebles/electrodomésticos"],
  ["UMX-154", "Muebles Dico Occidente", "(Individual) Muebles Dico Occidente", "Occidente", "Mueblerias", "Muebles/hogar"],
  ["UMX-155", "Nalúa Outlet", "(Individual) Nalúa Outlet", "Bajío", "Otros", "Outlet línea blanca/electrodomésticos"],
  ["UMX-181", "Aká Superbodega", "(Individual) Aká Superbodega", "Sureste", "Retail Regional", "Autoservicio regional"],
  ["UMX-170", "Arteli", "(Individual) Arteli", "Norte", "Retail Regional", "Autoservicio regional"],
  ["UMX-194", "Centro Comercial Cruz Azul", "(Individual) Centro Comercial Cruz Azul", "Centro", "Retail Regional", "Autoservicio"],
  ["UMX-184", "Comercial Balandra", "(Individual) Comercial Balandra", "Noroeste", "Retail Regional", "Línea blanca, electrodomésticos, electrónica"],
  ["UMX-185", "Comercial San Luis", "(Individual) Comercial San Luis", "Bajío", "Retail Regional", "Línea blanca, electrodomésticos"],
  ["UMX-188", "El Florido", "(Individual) El Florido", "Noroeste", "Retail Regional", "Autoservicio regional"],
  ["UMX-195", "Fénix El Super de Casa", "(Individual) Fénix El Super de Casa", "Golfo/Sureste", "Retail Regional", "Autoservicio"],
  ["UMX-189", "Garcés", "(Individual) Garcés", "Sur", "Retail Regional", "Autoservicio regional"],
  ["UMX-180", "La Marina", "(Individual) La Marina", "Golfo/Sureste", "Retail Regional", "Línea blanca, electrodomésticos, hogar"],
  ["UMX-196", "La Misión Supermercados", "(Individual) La Misión Supermercados", "Noroeste", "Retail Regional", "Autoservicio"],
  ["UMX-174", "Merco", "(Individual) Merco", "Norte", "Retail Regional", "Autoservicio regional"],
  ["UMX-197", "Más Bodega y Logística", "(Individual) Más Bodega y Logística", "Noroeste", "Retail Regional", "Autoservicio"],
  ["UMX-190", "PDH Puebla", "(Individual) PDH Puebla", "Centro", "Retail Regional", "Enseres menores/electrodomésticos"],
  ["UMX-191", "PDH Veracruz", "(Individual) PDH Veracruz", "Golfo/Sureste", "Retail Regional", "Enseres menores/electrodomésticos"],
  ["UMX-198", "Piticó", "(Individual) Piticó", "Sureste", "Retail Regional", "Autoservicio"],
  ["UMX-176", "S-Mart", "(Individual) S-Mart", "Norte", "Retail Regional", "Autoservicio regional"],
  ["UMX-177", "Smart", "(Individual) Smart", "Norte", "Retail Regional", "Autoservicio regional"],
  ["UMX-199", "Su Bodega", "(Individual) Su Bodega", "Golfo/Sureste", "Retail Regional", "Autoservicio"],
  ["UMX-203", "Su Plaza", "(Individual) Su Plaza", "Centro", "Retail Regional", "Autoservicio"],
  ["UMX-178", "Super Willys", "(Individual) Super Willys", "Sureste", "Retail Regional", "Autoservicio regional"],
  ["UMX-201", "Supermercados Aramburo", "(Individual) Supermercados Aramburo", "Noroeste", "Retail Regional", "Autoservicio"],
  ["UMX-200", "Súper Gutiérrez", "(Individual) Súper Gutiérrez", "Norte", "Retail Regional", "Autoservicio"],
  ["UMX-202", "Súper San Francisco de Asís", "(Individual) Súper San Francisco de Asís", "Sureste", "Retail Regional", "Autoservicio"],
  ["UMX-179", "Tiendas Garcés", "(Individual) Tiendas Garcés", "Sur", "Retail Regional", "Autoservicio regional"],

].map(([id, name, group, territory, channel, subchannel]) => ({ id, name, group, territory, channel, subchannel })) as readonly AlfaUniverseAccount[];

